// ============================================
// TRANSLATIONS - English
// ============================================

export const en = {
  // Navigation
  language: 'Language',
  switchLanguage: 'Switch Language',

  // Intro Scene
  intro: {
    title: 'GiftGhost',
    subtitle: 'Gift hunting made fun & easy!',
    cta: 'Find a Gift',
    socialProof: '10,000+ happy gift-givers',
  },

  // Input Scene
  input: {
    header: "⚡ How should we help?",
    subtitle: "Choose your style ↓",

    // Mode Cards
    modes: {
      detective: {
        label: 'Detective',
        shortDesc: 'Analyze a link',
        description: "Share a social media profile and we'll uncover hidden interests! 🔍",
        hint: 'Try: Instagram, Twitter, TikTok links...',
        tips: 'More posts = better insights!',
      },
      listener: {
        label: 'Listener',
        shortDesc: 'Dump your thoughts',
        description: 'Share everything you know about your friend. We\'ll find the gems! 💎',
        hint: 'What do they love? Hate? Dream about?',
        tips: 'Random details often lead to perfect gifts!',
      },
      interview: {
        label: 'Quick Chat',
        shortDesc: '3 questions',
        description: 'Answer 3 quick questions. Easy peasy! ✨',
        hint: '',
        tips: 'Short answers work too!',

        // Interview questions
        pain: {
          label: 'What frustrates them?',
          prefix: 'What frustrates them is...',
        },
        joy: {
          label: 'What makes them happy?',
          prefix: 'What makes them happy is...',
        },
        secret: {
          label: 'A hidden desire?',
          prefix: 'What they secretly want is...',
        },
      },
    },

    // Character count feedback messages
    charFeedback: {
      gettingThere: 'Keep going...',
      niceDetail: 'Nice detail! 💪',
      onFire: "You're on fire! 🔥",
      perfection: 'Perfection! 🌟',
    },

    // Placeholders
    placeholder: {
      detective: 'Paste a social link...',
      listener: 'Tell me about them...',
    },

    // Hints
    hint: '💡 More details = better recommendations!',

    // Button
    startTyping: 'Start Typing →',
    findGift: 'Find Perfect Gift',
  },

  // Thinking Scene
  thinking: {
    badge: 'Ghost is conjuring...',
    stages: {
      analyzing: 'Reading your thoughts 👀',
      digging: 'Uncovering hidden gems 💎',
      matching: 'Matching like crazy ⚡',
      generating: 'Wrapping up a surprise 🎁',
      finalizing: 'Almost there! Just a sec ✨',
    },
    rotatingLogs: [
      'Figuring out this person...',
      'Found something interesting...',
      'Summoning gift spirits...',
      'Looking for inspiration...',
      'Connecting the dots...',
      'Almost done!',
    ],
    funFact: {
      header: 'Did you know?',
      content: 'The average person spends',
      highlight: '7 hours',
      suffix: 'searching for the perfect gift. We\'re here to fix that! 🎯',
    },
  },

  // Reveal Scene
  reveal: {
    badge: '🏆 We found something perfect!',
    personaTitle: 'This is who your friend is! 🎉',

    insightLabels: {
      painPoint: 'Pain Point',
      obsession: 'Obsession',
    },

    giftCard: {
      label: '✨ PERFECT GIFT ✨',
      findButton: 'Find It Now',
      priceLabel: '💰',
    },

    actions: {
      tryAnother: 'Try Another',
      share: 'Share',
    },

    footer: {
      text: "You're going to be the best gift-giver!",
    },
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
  },

  // Errors
  errors: {
    apiKey: 'The Ghost is confused. (Check API Key)',
    network: 'Network connection failed',
    unknown: 'Unknown error',
  },

  // Stage / General
  stage: {
    error: {
      title: 'Oops!',
      message: 'Something went wrong. Try again?',
      button: 'OK',
    },
    share: {
      title: 'GiftGhost',
      text: 'I found the perfect gift!',
    },
  },

  // Share Card
  shareCard: {
    logo: 'GiftGhost 🎁',
    painPoint: 'PAIN POINT',
    obsession: 'OBSESSION',
    perfectGift: 'PERFECT GIFT',
    footer: 'Generated by GiftGhost',
    website: 'giftghost.com',
    priceSymbol: '💰',
    saveImage: 'Save Image',
    shareResult: 'Share Result',
    shareTitle: 'Gift for ${persona}',
    shareText: 'I found the perfect gift: ${gift}!',
  },
};
